version: '3'

services:
  app:
    image: 'create-credit:latest'
    build:
      context: .
    container_name: application
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/create_credit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root123
      - DEFAULT_DMIN_USERNAME=admin@admin.pl
      - DEFAULT_DMIN_PASSWORD=admin
      - DEFAULT_SYSTEM_USERNAME=automate@system.usr
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=create_credit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root123
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d